version: "3.8"

# laradock network
# networks:
#   web_service:
#     name: laradock_backend
#     external: true

services:
  api_server:
    build:
        context: ./
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/app
    environment:
      - TZ=Asia/Taipei
    init: true
    restart: always

    # laradock network
    # networks:
    #   - web_service